import React, { createContext, useContext, useState } from 'react';

// Create Cart Context
const CartContext = createContext();

// Custom hook to use cart context
export const useCart   = () => {
  const context = useContext(CartContext);
  if (!context) {
    throw new Error('useCart must be used within a CartProvider');
  }
  return context;
};

// Product data for cart items
const productData = {

 // petcare start
 7:{
    id: 7,
    name: "Pedigree Adult Dog Dry Food (Chicken and Vegetables)",
    weight: "1kg",
    price: 256,
    oldPrice: 360,
    discount: "29% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/0a27b202-9f8e-4374-b0cd-b5d013d801f1.png",
    inStock: false,
  },
  8:{
    id: 8,
    name: "Pedigree Adult Dog Dry Food (Chicken and Vegetables)",
    weight: "2.8kg",
    price: 589,
    oldPrice: 655,
    discount: "10% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=540/da/cms-assets/cms/product/0a27b202-9f8e-4374-b0cd-b5d013d801f1.png",
    inStock: true,
  },
  9: {
    id: 9,
    name: "Pedigree Puppy Dog Dry Food (Chicken and Milk",
    weight: "1 kg",
    price: 290,
    oldPrice: 320,
    discount:"9% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/5fd12876-6de4-46eb-a53a-e17887b2a6a5.png",
    inStock: true,
  },
  10: {
    id: 10,
    name: "Drools Adult (Chicken and Vegetables)",
    weight: "3kg",
    price: 739,
    oldPrice: 849,
    discount: "13% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/9d4592ce-fcf8-4438-b0c7-4fa7c1a59141.png",
    inStock: true,
  },
  11: {
    id: 11,
    name: "Pedigree Adult Wet Food (Chicken & Liver)",
    weight: "70g (30pcs)",
    price: 1274, 
    oldPrice: 1500,
    discount: "15% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/7269b332-e28f-4dcc-8fd2-f9de5eb55214.png",
    inStock: false,
  },
  12:{
    id: 12,
    name: "Pedigree Adult (Chicken and Vegetables)",
    weight: "370 g",
    price: 100,
    oldPrice: 110,
    discount: "9% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=540/da/cms-assets/cms/product/0a27b202-9f8e-4374-b0cd-b5d013d801f1.png",
    inStock: true,
  },
  13:{
    id: 13,
    name: "Pedigree Puppy (Chicken and Milk) ",
    weight: "370 g",
    price: 110,
    oldPrice: 120,
    discount: "8% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/5fd12876-6de4-46eb-a53a-e17887b2a6a5.png",
    inStock: true,
  },
  14: {
    id: 14,
    name: "Drools Puppy (Chicken and Eggs)",
    weight: "5kg",
    price: 819, 
    oldPrice: 999,
    discount: "18% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/63acc207-13a7-49cd-8592-1ddebc2a965d.png",
    inStock: true,
  },
  15: {
    id: 15,
    name: "Pedigree Puppy Wet Food (Chicken Chunks)",
    weight: "70g (30pcs)",
    price: 1290,
    oldPrice: 1500,
    discount: "14% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/f1e3246e-c27a-47d1-9c90-d8b3ead8a218.png",
    inStock: true,
  },
  16: {
    id: 16,
     name: "Whiskas Adult Dry Cat Food- Ocean Fish Flavour",
    weight: "480g",
    price: 184,
    oldPrice: 235,
    discount: "22% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=480,h=480/da/cms-assets/cms/product/85b37723-4247-4400-9efd-3ef4f4f648a1.jpg",
    inStock: true,
  },
  17: {
    id: 17,
    name: "Pedigree Puppy Wet Food (Chicken Chunks)",
    weight: "70 g",
    price: 50,
    oldPrice: 60,
    discount: "17% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/32c9a37c-d670-4cf6-a4bb-c6d82101482d.png",
    inStock: true,
  },
  18: {
    id: 18,
    name: "Pedigree Adult Wet Food (Chicken & Liver)",
    weight: "70 g",
    price: 50,
    oldPrice: 60,
    discount: "17% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/3d3ce5f4-e555-47d1-b193-c56ad228411d.png",
    inStock: true,
  },
  19: {
    id: 19,
    name: "Whiskas Wet Kitten Food- Chicken in Gravy",
    weight: "80 g (5pcs)",
    price: 245,
    oldPrice: 250,
    discount: "2% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/b49fd384-a0a6-447a-bf2c-3f093f7d8d67.png",
    inStock: true,
  },
  20: {
    id: 20,
    name: "Whiskas Wet Kitten Food- Tuna in Jelly",
    weight: "80 g (5pcs)",
    price: 245,
    oldPrice: 250,
    discount: "2% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/4cc3596d-233e-4ada-b934-4cb8ee8522be.png",
    inStock: true,
  },
21:{
    id: 21,
    name: "Whiskas Adult Dry Cat Food- Chicken Flavour",
    weight: "1.2kg",
    price: 336,
    oldPrice: 450,
    discount: "25% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/b945f4df-7a96-4880-a3ba-6640d02b8931.png",
    inStock: true,
  },
  22: {
    id: 22,
    name: "Whiskas Adult Dry Cat Food- Tuna Flavour",
    weight: "3kg",
    price: 979,
    oldPrice: 1120,
    discount: "13% OFF",
    image: "https://cdn.grofers.com/da/cms-assets/cms/product_videos_thumbnails/570e2fbd-7d05-48ab-8e96-14e6c94f5197.jpg",
    inStock: true,
  },
  // ... (remaining products with updated prices where available, inStock: true, and keeping original for others)
  23: {
    id: 23,
   name: "Whiskas Wet Kitten Food- Chicken in Gravy",
    weight: "80 g ",
    price: 40,
    oldPrice: 50,
    discount: "20% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/96ad42aa-e5b8-42c2-87ad-a4fb10b1fe9f.png",
    inStock: true,
  },
  24: {
    id: 24,
    name: "Whiskas Wet Kitten Food- Tuna in Jelly",
    weight: "80 g",
    price: 40,
    oldPrice: 50,
    discount: "20% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/66d4a9c5-cf2a-49e5-a99f-cbf4b5e83076.png",
    inStock: true,
  },
  25: {
    id: 25,
    name: "Drools Adult (Chicken and Egg)",
    weight: "3kg",
    price: 819,
    oldPrice: 999,
    discount: "18% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/9d4592ce-fcf8-4438-b0c7-4fa7c1a59141.png",
    inStock: true,
  },
  26: {
    id: 26,
    name: "Drools Adult (Meat and Rice)",
    weight: "3kg",
    price: 819,
    oldPrice: 999,
    discount: "18% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/9d4592ce-fcf8-4438-b0c7-4fa7c1a59141.png",
    inStock: true,
  },
  27: {
    id: 27,
    name: "Drools Adult (Chicken and Egg)",
    weight: "1kg",
    price: 300,
    oldPrice: 350,
    discount: "14% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/9d4592ce-fcf8-4438-b0c7-4fa7c1a59141.png",
    inStock: true,
  },
  
  28: {
    id: 28,
     name: "Whiskas Adult Dry Cat Food- Chicken Flavour",
    weight: "3kg",
    price: 979,
    oldPrice: 1120,
    discount: "13% OFF",
    image: "https://cdn.grofers.com/da/cms-assets/cms/product_videos_thumbnails/f04bd8f4-31fd-41b2-9961-3bb88b0f32c6.jpg",
    inStock: false,
  },
  // Note: For truncated products (id 29-61), keep original prices and add inStock: true. Update if current prices are available from further searches.
 29: {
    id: 29,
    name: "Mamy Poko Pants (XL)",
    weight: "22 pants",
    price: 320,
    oldPrice: 399,
    discount: "20% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/3e44ce9c-ce6a-409f-af15-aaf6dc96508e.png",
    inStock: true,
  },
  30: {
    id: 30,
    name: "Mamy Poko Pants (NB)",
    weight: "42 pants",
    price: 320,
    oldPrice: 390,
    discount: "20% OFF",
    image: "https://m.media-amazon.com/images/I/61NkERTWYeL._SY450_.jpg",
    inStock:true,
  },
  31: {
    id: 31,
    name: "Mamy Poko Pants (L)",
    weight: "28 Pants",
    price: 320,
    oldPrice: 390,
    discount: "20% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/135x164/18060687a.webp",
    inStock:true,
  },
  32: {
    id: 32,
     name: "Mamy Poko Pants (XXL)",
    weight: "17 Pants",
    price: 320,
    oldPrice: 390,
    discount: "20% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/19205952a.webp",
    inStock:true,
  },
  33: {
    id: 33,
    name: "Mamy Poko Pants (S)",
    weight: "38 Pants",
    price: 320,
    oldPrice: 390,
    discount: "20% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/18060685a.webp",
    inStock:true,
  },
  34: {
    id: 34,
    name: "Mamy Poko Pants (M)",
    weight: "38 Pants",
    price: 320,
    oldPrice: 390,
    discount: "20% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/18060686a.webp",
    inStock:true,
  },
  35: {
    id: 35,
    name: "Mamy Poko Pants (M)",
    weight: "16 Pants",
    price: 190,
    oldPrice: 210,
    discount: "10% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/18060686a.webp",
    inStock:true,
  },
  36: {
    id: 36,
    name: "Mamy Poko Pants (XL)",
    weight: "11 Pants",
    price: 190,
    oldPrice: 210,
    discount: "10% OFF",
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/3e44ce9c-ce6a-409f-af15-aaf6dc96508e.png",
    inStock:true,
  },
  37: {
    id: 37,
    name: "Mamy Poko Pants (L)",
    weight: "14 Pants",
    price: 190,
    oldPrice: 210,
    discount: "10% OFF",
      image: "https://cdn.fcglcdn.com/brainbees/images/products/135x164/18060687a.webp",
    inStock:true,
  },
  38: {
    id: 38,
    name: "Mamy Poko Pants (S)",
    weight: "20 Pants",
    price: 190,
    oldPrice: 210,
    discount: "10% OFF",
    image: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/18060685a.webp",
    inStock:true,
  },
  39: {
    id: 39,
    name: "StayFree Secure Cotton Soft Sanitary pads(Regular)",
    weight: "18 units",
    price: 99,
    oldPrice: 105,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/9a16dbba-d8d2-4e00-a270-32e2c6b20e56.png",
    inStock: true,
  },
  40: {
    id: 40,
    name: "Whisper Skin Love Soft (Ultra)",
    weight: "XL+ (6 pads)",
    price: 80,
    oldPrice: 85,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/6e0d9082-16ac-4825-8727-648597e187fc.jpg?dpr_multiplier=3.00",
    inStock:true,
  },
  41: {
    id: 41,
    name: "Whisper Bindazz Nights (XXXL)",
    weight: "XXXL+ (10 pads)",
    price: 315,
    oldPrice: 350,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/4576bdc5-b8f5-4ff4-951d-e245e8c536ea.png",
    inStock:true,
  },
  42: {
    id: 42,
    name: "Whisper Choice (XL)",
    weight: "XL (18 pads)",
    price: 114,
    oldPrice: 120,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/da/cms-assets/cms/product/d9ff9270-eede-4c2d-8064-bb94ab6bd062.png",
    inStock:true,
  },
  43: {
    id: 43,
   name: "StayFree Secure (XL)",
    weight: "XL (18 pads)",
    price: 118,
    oldPrice: 124,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/b114d676-9bba-44db-8b6d-a0a84ef08fc4.jpg?dpr_multiplier=3.00",
    inStock:true,
  },
  44: {
    id: 44,
    name: "StayFree Secure (XL)",
    weight: "XL (12 pads)",
    price: 80,
    oldPrice: 84,
    discount: "5% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/8455c6fe-510c-4b21-803a-14305d535ff0.png",
    inStock:true,
  },
  45:{
   
    id: 45,
    name: "Whisper Bindazz NIghts (XXL+)",
    weight: "XXL+ (5 pads)",
    price: 150,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/da/cms-assets/cms/product/9803f479-5596-450f-8f5b-260fc1ee07ca.jpg",
    inStock:true,
  },
  // ... continue for all up to 61 with inStock: true
  // dairy bread eggs
   46:{
    id: 46,
    name: "Amul Milk (FullCream)",
    weight: "500 ml",
    price: 35,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/628c97e0-5ed4-425d-a667-1d3bfa6f0bde.png",
    inStock:true,
  },
  47: {
    id: 47,
    name: "Amul Milk (Toned)",
    weight: "500 ml",
    price: 29,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/5734b087-3ad9-485f-bbe2-52079cd9e35d.png",
    inStock:true,
  },
  48: {
    id: 48,
    name: "Amul Cow Milk",
    weight: "500 ml",
    price: 30,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/ae29e828-f5d9-4f8b-89b6-8c6d6919df7b.png",
    inStock:true,
  },
  49:{
    id: 49,
    name: "MotherDairy Cow Milk",
    weight: "500 ml",
    price: 30,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/60065a08-2486-4f67-b2ae-e03670b2c8f3.png",
    inStock:true,
  },
  50:{
    id: 50,
    name: "MotherDairy Milk (FullCream)",
    weight: "500 ml",
    price: 35,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/c1d65f38-031a-4028-8bf6-a5fc2f0e288d.png",
      inStock:true,
  },
  51:{
    id: 51,
    name: "Amul Masti Curd (Dahi)",
    weight: "500 ml",
    price: 35,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/2107cdc3-8d54-41fb-a7ee-89d8573b9f06.jpg?dpr_multiplier=3.00",
      inStock:true,
  },
  52:{
    id: 52,
    name: "MotherDairy Curd (Dahi)",
    weight: "500 ml",
    price: 35,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/2b146201-870b-4bb8-aee7-8ef0377cbe2b.png",
      inStock:true,
  },
  53:{
    id: 53,
    name: "Amul Butter",
    weight: "100 gm",
    price: 62,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=360/da/cms-assets/cms/product/613787ac-f983-4cfb-b534-e219c8d47b39.png",
      inStock:true,
  },
  54:{
  id: 54,
    name: "Amul Butter",
    weight: "500 gm",
    price: 295,
    oldPrice: 305,
    discount: "3% OFF",
    image: "https://tse2.mm.bing.net/th/id/OIP.sRga9Of05-eQKbJLBtGbswHaHa?pid=Api&P=0&h=180",
      inStock:true,
  },
  55:{
    id: 55,
   name: "Amul Butter",
    weight: "200 gm",
    price: 128,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=360/da/cms-assets/cms/product/03af3633-5fa5-438f-bece-145ed114d279.png",
     inStock:true,  
  },
  
  56:{
    id: 56,
    name: "Delicious Butter",
    weight: "100 gm",
    price: 22,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/8a565e7f-22dc-4146-ac66-b099f5110293.jpg?dpr_multiplier=3.00",
      inStock:true,
  },
  57:{
  id: 57,
    name: "Delicious Butter",
    weight: "500 gm",
    price: 105,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.NbU9NdF84R9X2FMM-_LMyQHaHa?pid=Api&P=0&h=180",
      inStock:true,
  },
  58:{
    id: 58,
   name: "Amul Mozrilla Cheese Diced",
    weight: "200 gm",
    price: 129,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/0bd593b2-6433-4a3e-a71d-8964618c5074.jpg?dpr_multiplier=3.00",
    inStock:true,
  },
  59:{
    id: 59,
    name: "Amul Cheese Slice",
    weight: "10pcs",
    price: 149,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/a501e65f-194b-4db2-abc9-6b7bb515349c.png",
      inStock:true,
  },
  60:{
  id: 60,
    name: "Amul Cheese Cube",
    weight: "1 pack (8pcs)",
    price: 135,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/52377f0e-2ee1-4d3f-a0d6-f34934b71f0f.png",
      inStock:true,
  },
  61:{
    id: 61,
   name: "Amul Cheese Slice",
    weight: "5 pcs",
    price: 85,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/a501e65f-194b-4db2-abc9-6b7bb515349c.png",
     inStock:true,
  },
  62:{
    id: 62,
   name: "Amul Cream",
    weight: "200ml",
    price: 70,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/app/assets/products/sliding_images/jpeg/740347d8-80b9-40eb-8de4-72b283acb7bc.jpg?dpr_multiplier=3.00",
     inStock:true,
  },
  63:{
    id: 63,
   name: "Amul Cream",
    weight: "1 Litre",
    price: 230,
    oldPrice: null,
    discount: null,
    image: "https://m.media-amazon.com/images/I/51pn7p9gnfL.jpg",
     inStock:true,
  },
 64: {
    id: 64,
    name: "Ananda Paneer",
    weight: "200 g",
    price: 90,
    oldPrice: 95,
    discount: "5% OFF",
    image: "https://tse1.mm.bing.net/th/id/OIP.YlYniI_xVLWB1HuuHKki9gHaEP?pid=Api&P=0&h=180",
     inStock:true,
  },
  65:{
    id: 65,
    name: "Amul Cheese Spread",
    weight: "200 g",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/d8ee0b72-3ada-4218-a1df-10efd53a11b4.png",
     inStock:true,
  },
  66:{
    id: 66,
    name: "English Oven Brown Bread",
    weight: "450g",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/0b267148-c2c6-4eae-9ecd-1e9a83569e3a.png",
    inStock:true,
   
  },
  67: {
    id: 67,
    name: "English Oven Milk Bread",
    weight: "400 g",
    price: 40,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/9f363c60-8b58-4e1a-8c20-9647247b7227.png",
    inStock:true,
  },
  68:{
    id: 68,
    name: "English Oven White Bread",
    weight: "600 g",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/04cb3d03-fa41-4229-82d1-67beb4d4cd7d.png",
    inStock:true,
  },
  69:{
    id: 69,
    name: "English Oven MultiGrain Bread",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/ff8853fd-1be8-48cf-893a-3f1616af322c.png",
    inStock:true,
  },
  70:{
    id:70,
    name: "English Oven Fruit Bun",
    weight: "2 pcs",
    price: 20,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/f4418ade-78c5-4405-9973-02c6c6db3289.png",
    inStock:true,
  },
  71:{
    id: 71,
    name: "English Oven Sandwich Bread",
    weight: "400 g",
    price: 40,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/fb337791-9328-4c38-a2ee-bc3bb20d204a.png",
    inStock:true,
  },
  72:{
    id: 72,
    name: "English Oven Burger",
    weight: "6pcs",
    price: 60,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/b232b090-361c-49ee-99a9-617eeac57aef.png",
    inStock:true,
  },
  73:{
    id: 73,
    name: "English Oven Pav",
    weight: "400 g",
    price: 45,
    oldPrice: null,
    discount: null,
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/951eaf30-2c8f-4032-bca6-51885222aa99.png",
    inStock:true,
  },



  // atta rice dal
   74: {
    id: 74,
    name: "Fortune Chhaki Fresh Atta",
    weight: "10 kg",
    price: 436,
    oldPrice:485,
    discount: "10% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/1754da9d-9ce1-4d51-9695-10c7f11e5209.png",
    inStock:true,
  },
   75: {
    id: 75,
    name: "Aashirwaad Shudhh Chakki Atta",
    weight: "10 kg",
    price: 440,
    oldPrice: 495,
    discount: "13% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/e7bddd47-28d5-4dc7-a194-d0cbdfdb4c19.jpg?dpr_multiplier=3.00",
    inStock:true,
  },
  76: {
    id: 76,
    name: "Fortune Chhaki Fresh Atta",
    weight: "5 kg",
    price: 220,
    oldPrice: 253,
    discount: "12% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/1754da9d-9ce1-4d51-9695-10c7f11e5209.png",
    inStock:true,
  },
   77: {
    id: 77,
    name: "Aashirvaad High Fibre Atta with MultiGrain",
    weight: "5 kg",
    price: 315,
    oldPrice: 371,
    discount: "15% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/99c07f65-9c5b-4fc4-927b-7be3f2bea854.png",
    inStock:true,
  },
   78: {
    id: 78,
    name: "NatureFresh Shudhh Chakki Atta",
    weight: "5 kg",
    price: 220,
    oldPrice: 260,
    discount: "15% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/6650cacf-5347-4108-a653-4355531be4fa.png",
    inStock:true,
   },
    79: {
    id: 79,
    name: "Aashirwaad Shudhh Chakki Atta",
    weight: "5 kg",
    price: 230,
    oldPrice: 285,
    discount: "18% oFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=90/da/cms-assets/cms/product/e7bddd47-28d5-4dc7-a194-d0cbdfdb4c19.jpg?dpr_multiplier=3.00",
    inStock:true,
  },
  80: {
    id: 80,
    name: "NatureFresh Shudhh Chakki Atta",
    weight: "10 kg",
    price: 435,
    oldPrice: 495,
    discount: "12% OFF",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=450/da/cms-assets/cms/product/6650cacf-5347-4108-a653-4355531be4fa.png",
    inStock:true,
  },
  81: {
    id: 81,
    name: "JAGAT STORE Gol Atta (MP Sharbati) ",
    weight: "10 kg",
    price: 480,
    oldPrice: null,
    discount: null,
    image: "https://daivikorganic.com/cdn/shop/products/4_3b7a5867-3758-4098-98bb-4eb444af492e.png?v=1670564660",
    inStock:true,
  },
  

  82: {
    id: 82,
    name: "Arhar dal",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://themill.in/wp-content/uploads/2021/06/arhar-dal-1.jpg",
       inStock:true,
  },
  83:  {
    id: 83,
    name: "Chana Dal",
    weight: "500 g",
    price: 55,
    oldPrice: null,
    discount: null,
    image: " https://twobrothersindiashop.com/cdn/shop/articles/chana-dal-benefits.png?v=1694585472&width=1024",
    inStock:true,
  },
   84: {
    id: 84,
    name: "Moong Sabut",
    weight: "500 g",
    price: 60,
    oldPrice: null,
    discount: null,
    image: " https://www.indianasapplepie.com/cdn/shop/files/greenwholemoong_2048x.jpg?v=1738085822",
       inStock:true,
  },
  85:  {
    id: 85,
    name: "Moong Chilka",
    weight: "500 g",
    price: 65,
    oldPrice: null,
    discount: null,
    image: " https://farmorgo.com/beta/uploads/products/9986.png",
       inStock:true,
  },
  86:  {
    id: 86,
    name: "Moong Dhuli",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://healthymiller.com/cdn/shop/files/Moong_dhuliPulse.png?v=1693903186",
       inStock:true,
  },
  87:  {
    id: 87,
    name: "Urad Sabut (Makhani Dal)",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://www.ritirivaaj.com/cdn/shop/products/sabuturad-1_33b75575-420a-471d-ba05-8c426d3b47d0.jpg?v=1621684975",
       inStock:true,
  },
   88: {
    id: 88,
    name: "Urad Dhuli",
    weight: "500 g",
    price: 80,
    oldPrice: null,
    discount: null,
    image: " https://tiimg.tistatic.com/fp/1/008/806/urad-dhuli-dal-634.jpg",
       inStock:true,
  },
   89: {
    id: 89,
    name: "Urad Chilka",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://images.jdmagicbox.com/quickquotes/images_main/urad-chilka-dal-2217518343-jws43rmk.jpg",
       inStock:true,
  },
   90: {
    id: 90,
    name: "Black Masoor Sabut",
    weight: "500 g",
    price: 55,
    oldPrice: null,
    discount: null,
    image: " https://www.jiomart.com/images/product/original/rvzjzkxnha/momsy-premium-quality-black-masoor-dal-sabut-kali-masoor-5kg-product-images-orvzjzkxnha-p598375118-2-202302140918.jpg?im=Resize%3D%28420%2C420%29",
       inStock:true,
  },
   91: {
    id: 91,
    name: "Red Masoor Sabut",
    weight: "500 g",
    price: 50,
    oldPrice: null,
    discount: null,
    image: " https://tse4.mm.bing.net/th/id/OIP.ryMozdF3NWKPS8ikdYK2_wHaHa?pid=Api&P=0&h=180",
      inStock:true,
  },
  92:  {
    id: 92,
    name: "Black Masoor Dali hui",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://tiimg.tistatic.com/fp/1/007/626/high-in-protein-organic-kali-masoor-dal-for-cooking-good-for-health--404.jpg",
      inStock:true,
  },
   93: {
    id: 93,
    name: "Red Masoor Dali hui",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://tse4.mm.bing.net/th/id/OIP.dcf2GnWz92w5zwddQqallgHaHa?pid=Api&P=0&h=180",
       inStock:true,
  },
   94: {
    id: 94,
    name: "Rajma (Chitra)",
    weight: "500 g",
    price: 75,
    oldPrice: null,
    discount: null,
    image: " https://krishidhara.com/wp-content/uploads/2025/03/51HBMav203L._AC_UF10001000_QL80_.webp",
      inStock:true,
  },
  95:  {
    id: 95,
    name: "Chole (Medium)",
    weight: "500 g",
    price: 65,
    oldPrice: null,
    discount: null,
    image: " https://apexherbex.com/wp-content/uploads/2023/04/KABULI-CHANA-2-scaled.jpg",
        inStock:true,
  },
   96: {
    id: 96,
    name: "Chole (Large)",
    weight: "500 g",
    price: 80,
    oldPrice: null,
    discount: null,
    image: " https://tse2.mm.bing.net/th/id/OIP.DhSDTiBQMvZ5e9pfs8YzoQHaF-?pid=Api&P=0&h=180",
        inStock:true,
  },
   97: {
    id: 97,
    name: "Mix Dal",
    weight: "500 g",
    price: 70,
    oldPrice: null,
    discount: null,
    image: " https://tse3.mm.bing.net/th/id/OIP.28dfGTVORb5hu1ouKB7tdwHaF9?pid=Api&P=0&h=180",
       inStock:true,
  },
   98: {
    id: 98,
    name: "Safed  Matar (Kulche Wali)",
    weight: "500 g",
    price: 45,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.2sKlIZne3xs5YY2aov-S6QHaHa?pid=Api&P=0&h=180",
       inStock:true,
  },
   99: {
    id: 99,
    name: "Kala Chana",
    weight: "500 g",
    price: 48,
    oldPrice: null,
    discount: null,
    image: " https://tse3.mm.bing.net/th/id/OIP.5YwHmaMZSLq6oVy55ABUlwHaFF?pid=Api&P=0&h=180",
      inStock:true,
  },
   100:{
    id: 100,
    name: "Red Rajma (Kashmiri)",
    weight: "500 g",
    price: 80,
    oldPrice: null,
    discount: null,
    image: " https://tse3.mm.bing.net/th/id/OIP.o57MmB8K6N7M-a_Mwv6P0gAAAA?pid=Api&P=0&h=180",
     inStock:true,
  },
   101:{
    id: 101,
    name: "Basmati Chawal Mini Tukda Rice",
    weight: "1 kg",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.EXeG4ltL6CnOR3xJkYDcpAHaHB?pid=Api&P=0&h=180",
     inStock:true,
  },
  102: {
    id: 102,
    name: "Basmati Chawal Tukda Rice",
    weight: "1 kg",
    price: 60,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.Cwm3iSEXkYHikmIFWbOGIQHaFW?pid=Api&P=0&h=180",
     inStock:true,
  },
  103: {
    id: 103,
    name: "Basmati Chawal Pona Rice",
    weight: "1 kg",
    price: 80,
    oldPrice: null,
    discount: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.rIQUkS9OXsEw6TsP6as3VgHaF_?pid=Api&P=0&h=180",
     inStock:true,
  },
104:{
    id: 104,
    name: "Basmati Chawal Sabut Rice(Pulav Rice)",
    weight: "1 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.7cKH8IzhwnrQ7ZrQfu0j6AHaEL?pid=Api&P=0&h=180",
     inStock:true,
  },
 105: {
    id: 105,
    name: "Golden Sella Rice/Pulav (Double Chhabhi)",
    weight: "1 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.31u8aYU-yOTvjF5VimdVCQHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
 106: {
    id: 106,
    name: "Golden Sella Rice/Pulav (Galaxy)",
    weight: "1 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.8Lfl5y7MzqrRQ0Pa5bDN0AHaGe?pid=Api&P=0&h=180",
     inStock:true,
  },
  107:{
    id: 107,
    name: "India Gate Mini Mogra Rice/Chawal",
    weight: "10 kg",
    price: 570,
    oldPrice: null,
    discount: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.gL30AQL72KKPK0rqP_HeIgHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  108:{
    id: 108,
    name: "India Gate Mogra Rice/Chawal",
    weight: "10 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.32S9ve2pOCeCOtjmb0XazgHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  109: {
    id: 109,
    name: "India Gate Dubar Rice/Chawal",
    weight: "5 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.XXgv42_mvsEobV6YxA4JSwHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  110: {
    id: 110,
    name: "India Gate Tibar Rice/Chawal",
    weight: "5 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.J3RMsJMTGDAyD9gJlcXfrAHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  111: {
    id: 111,
    name: "India Gate Super Rice/Chawal",
    weight: "5 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.e6MMuqUpOz3bLbtGf1eaJQHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  112: {
    id: 112,
    name: "Delhi Pasand Easy Rice/Chawal",
    weight: "10 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.tKJv7dXqAP1SwggFv6hjJgAAAA?pid=Api&P=0&h=180",
     inStock:true,
  },
  113:{
    id: 113,
    name: "Delhi Pasand Light Rice/Chawal",
    weight: "10 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.MLd8SIuPq1mDP-6eBwLsfAHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  114:{
    id: 114,
    name: "Delhi Pasand Regular Rice/Chawal",
    weight: "10 kg",
    price: 110,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.7mrKDFFD2tCOvxoB6vQ7qwAAAA?pid=Api&P=0&h=180",
     inStock:true,
  },
  115:{
    id: 115,
    name: "Sona Mansuri Chawal/Rice",
    weight: "1 kg",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.zLl7VDcZr9lywelwILpCpQAAAA?pid=Api&P=0&h=180",
     inStock:true,
  },
  116:{
    id: 116,
    name: "Daawat Rozana Super Chawal/Rice",
    weight: "5 kg",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.xFumiJNBKLemWzxoWRGaiQHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  117: {
    id: 117,
    name: "Daawat Brown Chawal/Rice",
    weight: "1 kg",
    price: 140,
    oldPrice: null,
    discount: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.s2jyNQAz1f8GDciYwKNNSQHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
   118:{
    id: 118,
    name: "Sugar (Chini)",
    weight: "1 kg",
    price: 45,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.vxdjEfDW2VeNqgW2bLppKgAAAA?pid=Api&P=0&h=180",
     inStock:true,
  },
 119:{
    id: 119,
    name: "Dhampur Sugar (Chini)",
    weight: "1 kg",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.OnaOndFEZf2rEZ6vU_FqSQHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
 120: {
    id: 120,
    name: "Dhampur Sugar (Chini)",
    weight: "5 kg",
    price: 275,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.7WrWzaMeVaGaStNY2ZOA4QHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
 121:{
    id: 121,
    name: "Uttam Sugar (Chini)",
    weight: "1 kg",
    price: 55,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.yYA03PLqCcFuMiuZx-4obwHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
 122:{
    id: 122,
    name: "uttam Sugar (Chini)",
    weight: "5 kg",
    price: 275,
    oldPrice: null,
    discount: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.yYA03PLqCcFuMiuZx-4obwHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },
  123:{
    id: 123,
    name: "Brown Sugar  (Chini)",
    weight: "1 kg",
    price: 95,
    oldPrice: null,
    discount: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.xQm4TyJ6j3iIqarWbG7YUwHaHa?pid=Api&P=0&h=180",
     inStock:true,
  },

};


// Cart Provider Component
export const CartProvider = ({ children }) => {
  const [cart, setCart] = useState({});

  // Add item to cart
  const addToCart = (productId) => {
    const product = productData[productId];
    if (!product || !product.inStock) {
      console.warn(`Product ${productId} is out of stock or not found.`);
      return; // Prevent adding out-of-stock or non-existent products
    }
    setCart(prevCart => ({
      ...prevCart,
      [productId]: (prevCart[productId] || 0) + 1
    }));
  };

  // Remove item from cart
  const removeFromCart = (productId) => {
    setCart(prevCart => {
      const newCart = { ...prevCart };
      if (newCart[productId] > 1) {
        newCart[productId] = newCart[productId] - 1;
      } else {
        delete newCart[productId];
      }
      return newCart;
    });
  };

  // Update quantity
  const updateQuantity = (productId, quantity) => {
    const product = productData[productId];
    if (!product || !product.inStock) {
      return; // Prevent updating for out-of-stock products
    }
    if (quantity <= 0) {
      setCart(prevCart => {
        const newCart = { ...prevCart };
        delete newCart[productId];
        return newCart;
      });
    } else {
      setCart(prevCart => ({
        ...prevCart,
        [productId]: quantity
      }));
    }
  };

  // Clear cart
  const clearCart = () => {
    setCart({});
  };

  // Get cart items with product details
  const getCartItems = () => {
    return Object.entries(cart).map(([productId, quantity]) => ({
      ...productData[productId],
      quantity
    })).filter(item => item.id); // Filter out undefined products
  };

  // Get total items count
  const getTotalItems = () => {
    return Object.values(cart).reduce((sum, quantity) => sum + quantity, 0);
  };

  // Get cart total price
  const getCartTotal = () => {
    return Object.entries(cart).reduce((sum, [productId, quantity]) => {
      const product = productData[productId];
      return sum + (product ? product.price * quantity : 0);
    }, 0);
  };

  const value = {
    cart,
    addToCart,
    removeFromCart,
    updateQuantity,
    clearCart,
    getCartItems,
    getTotalItems,
    getCartTotal
  };

  return (
    <CartContext.Provider value={value}>
      {children}
    </CartContext.Provider>
  );
};

export default CartProvider;